import numpy as np

def setFilterCutoff(filter: int, cutoff: float) -> int: ...
def setFilterQfactor(filter: int, qfactor: float) -> None: ...
def addPlot(freq: np.ndarray, magnitude: np.ndarray, name: str) -> None: ...
def removePlot(name: str) -> None: ...